#!/bin/sh

# Save this file as ".git/hooks/pre-commit" in your
# git repository and set it to executable.
#
# To use the "go vet" command:
#   $ go get -v code.google.com/p/go.tools/cmd/vet
# To use the "golint" command:
#   $ go get -v github.com/golang/lint/golint

# go build >/dev/null 2>&1
# if [ $? -ne 0 ]
# then
# 	echo "Failed to build project. Please check the output of"
# 	echo "go build or run commit with --no-verify if you know"
# 	echo "what you are doing."
# 	exit 1
# fi

# try to create commit_logs folder
mkdir -p commit_logs

go fmt ./... >/dev/null 2>&1
if [ $? -ne 0 ]
then
	echo "'go fmt': Failed to run. This shouldn't happen. Please"
	echo "check the output of the command to see what's wrong"
	echo "or run commit with --no-verify if you know what you"
	echo "are doing."
	exit 1
fi

golint -set_exit_status ./... >commit_logs/linter.log 2>&1
if [ $? -ne 0 ]
then
	echo "'golint': has detected potential issues in the project."
	echo "Please check the output of 'golint' in: 'commit_logs/linter.log'"
	exit 1
fi

go vet ./... >commit_logs/vet.log 2>&1
if [ $? -ne 0 ]
then
	echo "'go vet': has detected potential issues in the project."
	echo "Please check the output of 'go vet' in: 'commit_logs/vet.log'"
	exit 1
fi

go test ./... >commit_logs/unit_tests.log 2>&1
if [ $? -ne 0 ]
then
	echo "'go test': Failed to run tests."
	echo "Please check the output of 'go test' in: 'commit_logs/unit_tests.log'"
	exit 1
fi