#!/bin/sh

# Save this file as ".git/hooks/pre-commit" in your
# git repository and set it to executable.
#
# To use the "go vet" command:
#   $ go get -v code.google.com/p/go.tools/cmd/vet
# To use the "golint" command:
#   $ go get -v github.com/golang/lint/golint
go fmt ./...
go vet ./...
golint .
# go test ./...